name: "My Workflow"
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Hello World"
  job2:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Hello 2"
  job3:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Hello 3"
    needs:
      - job1
      - job2
  job4:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Hello 4"
    needs:
      - job3
