name: "Checking Github Action Skills"
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-22.04
    name: "Job 1"
    steps:
      - name: "First Step"
        run: echo "hello From First step"
  job2:
    runs-on: ubuntu-22.04
    name: "JOb 2"
    steps:
      - name: "Job 2"
        run: echo "Hello From Job 2"
      - run: ls -a
